---
title: "Covid deaths in Belgium"
author: "Max Derie"
date: "08/09/2020"
draft: false
slug: covidBE
---

```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
```


```{r}

raw <- 
  read_csv(here::here("content/blogs/data","covid-19-pandemic-belgium-deaths-agesexdate.csv")) %>% 
  select(-";;;;;;;;;;;;;;;;;;;;;") #additional column that shows up

glimpse(raw)

```


```{r}
data <- raw %>%
  drop_na() %>%  
  mutate(Date = ymd(paste(as.character(Year), as.character(Month), as.character(Day))))

data <- data %>% 
  pivot_wider(names_from = c(Region, Agegroup, Sex), values_from = Deaths, values_fill = 0) %>% #pivot wider to add missing values (need one for each combination of sex, region, age group and date)
  pivot_longer(cols = -c(Year, Month, Day, Date), names_to = c("Region", "Agegroup", "Sex"), names_sep = "_", values_to = "Deaths") #convert back to long format
  
```

```{r}

data %>% 
  group_by(Agegroup, Date) %>% 
  summarise(total_deaths = sum(Deaths)) %>% 

  ggplot(aes(Date, total_deaths, fill = Agegroup)) +
  geom_area(position="stack") +
  labs(x = "Date", y = "Deaths", title = "Evolution of Covid deaths throughout the evolution of the pandemic")
  
```
```{r}
data %>% 
  group_by(Agegroup) %>% 
  summarise(total_deaths = sum(Deaths)) %>%
  mutate(prop_deaths = total_deaths/sum(total_deaths)) %>% 
  
  
  ggplot(aes(x = reorder(Agegroup, -total_deaths), y = total_deaths, fill = Agegroup, label = scales::percent(prop_deaths))) + 
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(labels = scales::comma) +
  geom_text(position = position_dodge(width = .9),    # move to center of bars
              vjust = -0.5,    # nudge above top of bar
              size = 3) + 
  labs(x = "Age group", y = "Deaths", title = "Number of Covid deaths per age group")
```

```{r}
data %>% 
  group_by(Region) %>% 
  summarise(total_deaths = sum(Deaths)) %>% 
  add_column(total_pop = c(1208542, 6589069, 3633795)) %>% 
  mutate(prop_deaths = total_deaths/total_pop) %>% 
  
  ggplot(aes(x = reorder(Region, -prop_deaths), y = prop_deaths, fill = Region)) + 
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(labels = scales::percent) +
  labs(x = NULL, y = NULL, title = "Deaths due to Covid as a proportion of regional population")

```
```{r}
data %>% 
  group_by(Agegroup, Sex) %>% 
  summarise(total_deaths = sum(Deaths)) %>% 
  pivot_wider(names_from = Sex, values_from = total_deaths, values_fill = 0) %>% 
  mutate(Male = M/(F+M), Female = 1-Male) %>% 
  select(Agegroup, Male, Female) %>% 
  pivot_longer(cols = -Agegroup, names_to = "Sex", values_to = "Proportion") %>% 
  
  
  ggplot(aes(Agegroup, Proportion, fill = Sex)) +
  geom_col(position = "stack") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Age group", title = "Proportion of covid victims according to sex and age")
```

